container_objects:
  - "handbag"
  - "backpack"

manipulable_objects:
  - "bottle"
  - "handbag"
  - "backpack"
  - "bowl"
  - "umbrella"
  - "laptop"
  - "mouse"
  - "keyboard"
  - "cell_phone"
  - "book"
  - "scissors"
  - "hair_drier"
  - "toothbrush"
  - "sink"
  - "knife"
  - "fork"

food_objects:
  - "apple"
  - "sandwich"
  - "orange"
  - "broccoli"
  - "carrot"
  - "hot_dog"
  - "pizza"
  - "donut"
  - "cake"

furniture_objects:
  - "chair"
  - "couch"
  - "bed"
  - "dining_table"
  - "toilet"
  - "tv"
  - "potted_plant"
  - "microwave"
  - "oven"
  - "refrigerator"
  - "vase"
  - "clock"

vehicule_objects:
  - "bicycle"
  - "car"
  - "motorcycle"
  - "airplane"
  - "bus"
  - "train"
  - "boat"
  - "truck"

living_thing:
  - "cat"
  - "dog"
  - "person"
  - "bird"
  - "horse"
  - "sheep"
  - "cow"
  - "bear"
  - "zebra"
  - "giraffe"
